[package]
name = "api"
version = "0.1.0"
authors = ["itrofimow <i.trofimow@yandex.ru>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.3"
futures = "0.1"
tokio = "0.1"
tokio-postgres = "0.4.0-rc.3"
